version: '3.8'


services:
  nginx:
    container_name: nginx
    build: dockerfiles/nginx
    depends_on:
      - gin-backend-api
    tty: true
    volumes:
# 左から右の場所にマウントされる（:区切り）
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8000:80"

  gin-backend-api:
    container_name: gin-backend-api
    build: dockerfiles/gin-backend
    depends_on:
      - postgresql
    tty: true


#    command:
    volumes:
      - .:/dockerfiles/gin-backend

    expose:
      - '3000'
    ports:
      - '8080:8080'
#    command: sh -c 'go mod tidy && air'

  postgresql:
    container_name: postgresql_db
    image: postgres:15.5-alpine3.19
    volumes:
      - db_data:/var/lib/pgsql
      # - ./sql_folder:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: ${DB_PASSWORD}
      POSTGRES_DB: blg_general
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.11
    volumes:
      - db_data:/var/lib/pgadmin4/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    depends_on:
      - postgresql
    ports:
      - "5050:80"

volumes:
  db_data: