FROM golang:1.21.5-alpine3.19


#
#RUN go mod init gin-backend-api
#RUN go mod tidy
#RUN apt-get update \
#    && apt-get install git \
#    && go get github.com/gin-gonic/gin \
#    && go get github.com/jinzhu/gorm \
#    && go install github.com/cosmtrek/air@latest


